### PR TITLE
Swift 4.0 compatibility

### PR DESCRIPTION
**Pull request by jjcastro**
Tried modifying the bare minimum to get it to work on my swift 4 app. Works nicely (but likely needs a lot of cleanup)

### CODE REVIEW

**Comment by phoney** [comment]
For some reason there are .DS_Store files in your PR. These files should never be included in a project like this. They should be excluded by the project .gitignore or by a global .gitignore, or both. I think you don't have a global .gitignore installed.

**Comment by jjcastro** [comment]
Woah you’re right, thanks! New dev setup.

**Comment by kevincador** [comment]
Should someone else make another PR? (I can do it with the same modifications @jjcastro did)
Or the PR can be updated?

**Comment by DavidLari** [comment]
The repo owner appears to no longer maintain this project. I have cloned and renamed it. I already have a Swift 4 version. https://github.com/DavidLari/Haring

**Comment by kevincador** [comment]
Okay. Witched to Haring. Thanks.

**Pull request merged**
