### PR TITLE
Fix parsing of markdown code element

### PR DESCRIPTION
**Pull request by macgeekpro**
This solves issue #8 whereby 2 anomalies occurred constantly when parsing grave accent to represent markdown element code. For example, let c1 = `this is code`, c2 = ```this is code too```

1) When either `c1`  or `c2`  occurs at the the beginning of a file, it will cause a runtime error.  

2) When either `c1` or `c2` occurs somewhere within the file, it doesn't cause a runtime error but as explained in #8, it outputs a random string of numbers. 

After further investigation, the culprit is in the regex string: `"(?<!\\\\)(?:\\\\\\\\)*+(`+)(._?[^`]._?)(\1)(?!`)"`. I am not good at regex yet but that's where the issue is. So, in my implementation, I modified the regex string and no anomaly occurs and thus no runtime error.

### CODE REVIEW

**Comment by ivanbruel** [comment]
This seems to have a lot of conflicts which need to be solved, will try working it out sometime soon.

**Comment by DavidLari** [comment]
Is this being worked on? I've found that simply trying to parse the following crashes and I think it's related:

\`\`\`test

**Comment by yoha** [comment]
@DavidLari Closing the triple ticks will prevent the crash as in ```test```. Although ideally, not closing keyword w/ triple ticks, the word simply will not get parsed as markdown format. I have tested this unclosing pattern on other markdown elements and they work ok.

**Comment by DavidLari** [comment]
The problem is I am creating a markdown editor using this library to show the preview. So, crashing on open ticks is a showstopper.

**Comment by bmoliveira** [comment]
This is already been fixed on other PR.

**Pull request closed without merging**
